### ISSUE TITLE
deploy branch 

### ISSUE THREAD

**Issue by aero9991** [leshiple/loftschool-project-3#4]
сбой в пропорциях(предположительно только ватермарк
![default](https://cloud.githubusercontent.com/assets/14896363/11163252/16cc72d0-8b03-11e5-8ffa-a7752567860f.PNG)
оригинал:
![genel_logo](https://cloud.githubusercontent.com/assets/14896363/11163265/38516654-8b03-11e5-90d7-71d69bf75c8e.png)

**Comment by leshiple** [comment]
Поправил
